# Main configuration

business:
  name: Pholicious Noodle Bar
  city: Lake Forest
  address:
    - "23532 El Toro Rd #15"
    - "Lake Forest, CA 92630"
  phoneNumber: (949) 345-1282
  hours:
    - Sun 10:00 am - 8:00 pm
    - Mon 10:00 am - 8:00 pm
    - Tue 10:00 am - 8:00 pm
    - Wed 10:00 am - 8:00 pm
    - Thu 10:00 am - 8:00 pm
    - Fri 10:00 am - 8:00 pm
    - Sat 10:00 am - 8:00 pm

# Links to external pages

googleMaps:
  embeddedMap: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3322.422167118595!2d-117.70083928479627!3d33.62029418072567!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80dce9467082635f%3A0x7dccaef9d85e6a90!2sPholicious%20Noodle%20Bar%20dba%20Pho%20Tung%20Cafe!5e0!3m2!1sen!2sus!4v1650238701421!5m2!1sen!2sus"
  directions: https://goo.gl/maps/t7JvNEyQxsdQtTtPA

fromTheRestaurant: https://fromtherestaurant.com/pho-tung--cafe-restaurant/locations/
yelp: https://www.yelp.com/biz/pholicious-noodle-bar-lake-forest
